import { fetchGatewayEvidence, gatewayDemoContract } from './gateway-client.js'
import { provisionalContribution } from './eml.js'

const state = { records: [], selectedId: null }
const $ = (id) => document.getElementById(id)
const controls = {
  search: $('searchInput'), status: $('statusFilter'), domain: $('domainFilter'), role: $('roleFilter'), priority: $('priorityFilter'), sort: $('sortFilter'),
}
const labels = {
  personal: 'Personal', performance_work: 'Performance & work', health_clinical_adjacent: 'Health & clinical-adjacent', not_applicable: 'Not applicable',
  direct_intervention: 'Direct intervention', evidence_synthesis: 'Evidence synthesis', protocol: 'Protocol', mechanism: 'Mechanism', measurement: 'Measurement', cross_domain: 'Cross-domain',
  high: 'High', medium: 'Medium', low: 'Low', approved: 'Human approved', provisional: 'Research watchlist', excluded: 'Boundary / excluded',
  assistant_adjudicated_not_human_approved: 'Assistant adjudicated · human review pending', human_approved: 'Human approved', reviewing: 'Screened · review pending', approved_seed: 'Approved seed', approved_release: 'Approved release',
}
function humanize(value){if(!value)return 'Not yet extracted';return labels[value]||String(value).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function formatDate(record){if(record.publication_date){const date=new Date(`${record.publication_date}T00:00:00Z`);return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(date)}return record.publication_year?String(record.publication_year):'Date not backfilled'}
function statusClass(status){return ['approved','provisional','excluded'].includes(status)?status:'provisional'}
function statusPill(record){const span=document.createElement('span');span.className=`status-badge ${statusClass(record.evidence_status)}`;span.textContent=humanize(record.evidence_status);return span}
function chip(text,className=''){const span=document.createElement('span');span.className=`meta-chip ${className}`.trim();span.textContent=text;return span}
function emlChip(record){const eml=provisionalContribution(record);const span=document.createElement('span');span.className=`eml-badge ${eml.colorToken}`;span.title=`${eml.basis} This is a provisional record-contribution level, not a body-level effectiveness rating.`;span.textContent=eml.level==null?'EML pending':`EML ${eml.level}`;return span}
function matches(record){const query=controls.search.value.trim().toLowerCase(),status=controls.status.value,domain=controls.domain.value,role=controls.role.value,priority=controls.priority.value;if(status!=='all'&&record.evidence_status!==status)return false;if(domain==='legacy'&&record.primary_domain)return false;if(domain!=='all'&&domain!=='legacy'&&record.primary_domain!==domain&&!record.domains.includes(domain))return false;if(role==='legacy'&&record.paper_role)return false;if(role!=='all'&&role!=='legacy'&&record.paper_role!==role)return false;if(priority==='legacy'&&record.priority)return false;if(priority!=='all'&&priority!=='legacy'&&record.priority!==priority)return false;if(!query)return true;const haystack=[record.title,record.venue,record.doi,record.pmid,record.evidence_note,record.paper_role,record.study_design,record.primary_domain,...(record.domains||[])].filter(Boolean).join(' ').toLowerCase();return haystack.includes(query)}
function sorted(records){const rows=[...records];if(controls.sort.value==='title')return rows.sort((a,b)=>a.title.localeCompare(b.title));const direction=controls.sort.value==='oldest'?1:-1;return rows.sort((a,b)=>{const ad=a.publication_date||`${a.publication_year||0}-01-01`,bd=b.publication_date||`${b.publication_year||0}-01-01`;return ad.localeCompare(bd)*direction||a.title.localeCompare(b.title)})}
function filteredRecords(){return sorted(state.records.filter(matches))}
function updateMetrics(){$('totalMetric').textContent=state.records.length;$('approvedMetric').textContent=state.records.filter(r=>r.evidence_status==='approved').length;$('provisionalMetric').textContent=state.records.filter(r=>r.evidence_status==='provisional').length;$('excludedMetric').textContent=state.records.filter(r=>r.evidence_status==='excluded').length;$('snapshotLabel').textContent=`Research snapshot · ${gatewayDemoContract.release.replace('hrp-evidence-gateway-demo-','')}`}
function renderList(){const records=filteredRecords();$('resultCount').textContent=records.length;const list=$('resultsList');list.replaceChildren();if(!records.length){const empty=document.createElement('div');empty.className='no-results';empty.textContent='No evidence records match these filters.';list.append(empty);renderDetail(null);return}if(!records.some(r=>r.source_id===state.selectedId))state.selectedId=records[0].source_id;for(const record of records){const button=document.createElement('button');button.type='button';button.className=`evidence-card ${record.source_id===state.selectedId?'selected':''}`;button.addEventListener('click',()=>{state.selectedId=record.source_id;renderList();renderDetail(record)});const top=document.createElement('div');top.className='card-top';const statusWrap=document.createElement('div');statusWrap.className='card-statuses';statusWrap.append(statusPill(record));if(record.evidence_status!=='excluded')statusWrap.append(emlChip(record));top.append(statusWrap);const date=document.createElement('span');date.className='card-date';date.textContent=formatDate(record);top.append(date);const title=document.createElement('h3');title.textContent=record.title;const venue=document.createElement('p');venue.className='card-venue';venue.textContent=record.venue||'Venue not backfilled';const chips=document.createElement('div');chips.className='card-chips';chips.append(chip(record.primary_domain?humanize(record.primary_domain):'Approved seed · domain not backfilled','muted'));if(record.paper_role)chips.append(chip(humanize(record.paper_role)));if(record.priority)chips.append(chip(`${humanize(record.priority)} priority`,'priority'));button.append(top,title,venue,chips);list.append(button)}renderDetail(records.find(r=>r.source_id===state.selectedId)||records[0])}
function infoItem(label,value){const item=document.createElement('div');item.className='detail-info-item';const key=document.createElement('span');key.textContent=label;const val=document.createElement('strong');val.textContent=value||'Not yet extracted';item.append(key,val);return item}
function lifecycle(record){const approved=record.evidence_status==='approved';const excluded=record.evidence_status==='excluded';const steps=[['Discover / deduplicate','complete','Source is visible in the governed research corpus.'],['Screen / classify',excluded?'boundary':'complete',excluded?'Retained as a scope/boundary case.':'Domain/role screening is available on this public card.'],['Retrieve / structured extraction',approved?'partial':'pending',approved?'Approved seed record; deeper route/outcome fields may still be incomplete on this public card.':'Full-text retrieval and structured extraction are not yet represented as complete here.'],['Appraise / synthesise',approved?'partial':'pending',approved?'Human-approved seed evidence; do not infer a body-level synthesis unless an approved claim is shown.':'Quality appraisal and synthesis are pending.'],['Human approve / release',approved?'complete':excluded?'boundary':'pending',approved?'Included in the current approved seed release.':excluded?'Not an included evidence claim.':'Not claims-safe until human review and release approval.']];const section=document.createElement('section');section.className='detail-section lifecycle-section';const h=document.createElement('h3');h.textContent='Flow 1 evidence lifecycle';const grid=document.createElement('div');grid.className='lifecycle-grid';for(const [name,status,note] of steps){const row=document.createElement('div');row.className=`lifecycle-step ${status}`;row.innerHTML=`<span>${name}</span><strong>${status==='complete'?'Complete':status==='partial'?'Partial / not fully exposed':status==='boundary'?'Boundary':'Pending'}</strong><small>${note}</small>`;grid.append(row)}section.append(h,grid);return section}
function effectivenessSection(record){const eml=provisionalContribution(record);const section=document.createElement('section');section.className='detail-section effectiveness-section';const h=document.createElement('h3');h.textContent='Provisional effectiveness-evidence contribution';const hero=document.createElement('div');hero.className='eml-summary';const badge=document.createElement('span');badge.className=`eml-badge large ${eml.colorToken}`;badge.textContent=eml.level==null?'EML pending':`EML ${eml.level}`;const text=document.createElement('div');const strong=document.createElement('strong');strong.textContent=eml.label;const p=document.createElement('p');p.textContent=eml.basis;text.append(strong,p);hero.append(badge,text);const boundary=document.createElement('p');boundary.className='eml-boundary';boundary.textContent='This is a provisional record-contribution code derived conservatively from the screening role. It is not a body-level effectiveness rating. EML 3–7 require evidence of replication, convergence, transfer/durability, real-world effectiveness or scale-readiness from structured extraction and appraisal.';section.append(h,hero,boundary);return section}
function renderDetail(record){const panel=$('detailPanel');panel.replaceChildren();if(!record){const empty=document.createElement('div');empty.className='empty-detail';empty.innerHTML='<div class="empty-detail-icon">↗</div><h3>Select an evidence record</h3><p>Review its authority, current maturity, CSI relevance and screening rationale.</p>';panel.append(empty);return}const hero=document.createElement('div');hero.className='detail-hero';const heroMeta=document.createElement('div');heroMeta.className='detail-status-row';heroMeta.append(statusPill(record));if(record.evidence_status!=='excluded')heroMeta.append(emlChip(record));heroMeta.append(chip(formatDate(record),'date-chip'));const title=document.createElement('h2');title.textContent=record.title;const citation=document.createElement('p');citation.className='detail-citation';citation.textContent=[record.venue,record.doi?`DOI ${record.doi}`:null,record.pmid?`PMID ${record.pmid}`:null].filter(Boolean).join(' · ')||'Bibliographic identifiers not fully backfilled';hero.append(heroMeta,title,citation);if(record.source_url){const link=document.createElement('a');link.className='primary-link';link.href=record.source_url;link.target='_blank';link.rel='noreferrer';link.textContent='Open source ↗';hero.append(link)}
const governance=document.createElement('section');governance.className=`detail-section governance-${statusClass(record.evidence_status)}`;const gt=document.createElement('h3');gt.textContent='Evidence status & authority';const gg=document.createElement('div');gg.className='detail-info-grid';gg.append(infoItem('Status',humanize(record.evidence_status)),infoItem('Authority',humanize(record.authority)),infoItem('Review state',humanize(record.review_status)),infoItem('Evidence class',humanize(record.review_bucket)));const statusNote=document.createElement('p');statusNote.className='governance-copy';statusNote.textContent=record.evidence_status==='approved'?'This record belongs to the current human-reviewed seed evidence release.':record.evidence_status==='excluded'?'This source is retained as a transparent scope/boundary case and is not treated as included intervention evidence.':'This is a screening-level research-watchlist record. Human verification, deeper extraction and scientific approval are still pending.';governance.append(gt,gg,statusNote)
const classification=document.createElement('section');classification.className='detail-section';const ct=document.createElement('h3');ct.textContent='Current public evidence fields';const cg=document.createElement('div');cg.className='detail-info-grid';cg.append(infoItem('Paper role',record.paper_role?humanize(record.paper_role):'Approved seed · role not backfilled'),infoItem('Study design',record.study_design),infoItem('Primary CSI domain',record.primary_domain?humanize(record.primary_domain):'Approved seed · domain not backfilled'),infoItem('Full-text priority',record.priority?humanize(record.priority):'Approved seed · priority not backfilled'),infoItem('Domains',record.domains.length?record.domains.map(humanize).join(', '):'Not yet extracted'),infoItem('Health scope',record.health_scope?humanize(record.health_scope):'Not yet extracted'));classification.append(ct,cg)
panel.append(hero,governance,lifecycle(record));if(record.evidence_status!=='excluded')panel.append(effectivenessSection(record));panel.append(classification);if(record.evidence_note){const note=document.createElement('section');note.className='detail-section';const nt=document.createElement('h3');nt.textContent=record.evidence_status==='approved'?'Evidence interpretation / seed note':'Screening rationale';const copy=document.createElement('p');copy.className='detail-note';copy.textContent=record.evidence_note;note.append(nt,copy);panel.append(note)}}
function resetFilters(){controls.search.value='';controls.status.value='all';controls.domain.value='all';controls.role.value='all';controls.priority.value='all';controls.sort.value='newest';state.selectedId=null;renderList()}
for(const control of Object.values(controls))control.addEventListener('input',renderList);$('clearFilters').addEventListener('click',resetFilters)
async function start(){const controller=new AbortController();try{state.records=await fetchGatewayEvidence(controller.signal);$('loadingState').hidden=true;updateMetrics();renderList()}catch(error){$('loadingState').hidden=true;const errorState=$('errorState');errorState.hidden=false;errorState.textContent=error instanceof Error?error.message:'Could not load the Evidence Gateway.'}}
void start()
