#!/usr/bin/env python3
"""Apply Stage 4 candidate outcome mappings to the local Evidence Registry.

The Stage 4 manifest lives outside the immutable 2026-08-23 release. Stable
identity uses source_id + outcome_name + legacy_rung + raw_timepoint because
normalized outcome_id values are regenerated by the historical importer.

Candidate mappings remain mapping_source=agent_candidate and
review_status=proposed. Existing human-reviewed/approved mappings are never
overwritten or deleted.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_CONTAINER = "supabase_db_research-platform"
DEFAULT_MANIFEST = REPO_ROOT / "components/evidence-registry/data/stage4_seed_mappings.v1.json"


def run(cmd: list[str], *, input_text: str | None = None, capture: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, input=input_text, text=True, check=True, capture_output=capture)


def psql(container: str, sql: str, *, tuples_only: bool = False) -> str:
    cmd = [
        "docker", "exec", "-i", container, "psql",
        "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres",
    ]
    if tuples_only:
        cmd.extend(["-A", "-t", "-F", "|"])
    result = run(cmd, input_text=sql, capture=tuples_only)
    return result.stdout.strip() if tuples_only else ""


def lit(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def stable_outcome_id(container: str, mapping: dict[str, object]) -> str:
    sql = f"""
select eo.outcome_id
from public.evidence_outcome eo
join public.study s on s.study_id = eo.study_id
where s.source_id = {lit(mapping['source_id'])}
  and eo.outcome_name = {lit(mapping['outcome_name'])}
  and eo.evidence_rung is not distinct from {lit(mapping.get('legacy_rung'))}
  and eo.timepoint is not distinct from {lit(mapping.get('raw_timepoint'))}
order by eo.outcome_id;
"""
    rows = [r.strip() for r in psql(container, sql, tuples_only=True).splitlines() if r.strip()]
    if len(rows) != 1:
        key = (
            mapping["source_id"], mapping["outcome_name"],
            mapping.get("legacy_rung"), mapping.get("raw_timepoint"),
        )
        raise SystemExit(f"Expected exactly one normalized outcome for stable key {key!r}; got {rows!r}")
    return rows[0]


def update_dimension_status(
    container: str,
    outcome_id: str,
    *,
    dimension: str,
    status: str,
    rationale: str | None,
    outcome_distance: str | None = None,
) -> None:
    if dimension == "distance":
        assignments = f"""
outcome_distance = {lit(outcome_distance)},
distance_status = {lit(status)},
distance_mapping_source = 'agent_candidate',
distance_review_status = 'proposed',
rationale = {lit(rationale)},
updated_at = now()
"""
    else:
        assignments = f"""
{dimension}_status = {lit(status)},
{dimension}_mapping_source = 'agent_candidate',
{dimension}_review_status = 'proposed',
rationale = {lit(rationale)},
updated_at = now()
"""

    psql(
        container,
        f"""
update public.outcome_stage4_classification
set {assignments}
where outcome_id = {outcome_id}
  and {dimension}_review_status = 'proposed'
  and {dimension}_mapping_source in ('migration', 'agent_candidate');
""",
    )


def replace_candidate_links(
    container: str,
    *,
    table: str,
    value_column: str,
    outcome_id: str,
    values: list[str],
    rationale: str | None,
) -> None:
    psql(
        container,
        f"""
delete from public.{table}
where outcome_id = {outcome_id}
  and mapping_source = 'agent_candidate'
  and review_status = 'proposed';
""",
    )

    for value in values:
        psql(
            container,
            f"""
insert into public.{table} (
  outcome_id, {value_column}, rationale, mapping_source, review_status
) values (
  {outcome_id}, {lit(value)}, {lit(rationale)}, 'agent_candidate', 'proposed'
)
on conflict (outcome_id, {value_column}) do nothing;
""",
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply Stage 4 candidate seed outcome mappings to local Supabase.")
    parser.add_argument("--container", default=DEFAULT_CONTAINER)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))

    running = run(
        ["docker", "inspect", "-f", "{{.State.Running}}", args.container],
        capture=True,
    ).stdout.strip()
    if running != "true":
        raise SystemExit(f"Local database container {args.container!r} is not running.")

    print(f"Applying Stage 4 candidate mappings: {manifest['manifest_version']} ({manifest['release_id']})")

    outcome_count = 0
    time_links = 0
    transfer_links = 0
    role_links = 0
    bridge_links = 0

    for mapping in manifest["mappings"]:
        outcome_id = stable_outcome_id(args.container, mapping)
        rationale = mapping.get("rationale")

        # The insert trigger should already have created this row, but retain an
        # idempotent fallback for non-standard local states.
        psql(
            args.container,
            f"""
insert into public.outcome_stage4_classification (
  outcome_id, legacy_rung_snapshot, raw_timepoint_snapshot, rationale
) values (
  {outcome_id}, {lit(mapping.get('legacy_rung'))}, {lit(mapping.get('raw_timepoint'))},
  'Stage 4 candidate classification status row.'
)
on conflict (outcome_id) do nothing;
""",
        )

        update_dimension_status(
            args.container,
            outcome_id,
            dimension="distance",
            status=mapping["distance_status"],
            rationale=rationale,
            outcome_distance=mapping.get("outcome_distance"),
        )
        update_dimension_status(
            args.container,
            outcome_id,
            dimension="time",
            status=mapping["time_status"],
            rationale=rationale,
        )
        update_dimension_status(
            args.container,
            outcome_id,
            dimension="transfer",
            status=mapping["transfer_status"],
            rationale=rationale,
        )
        update_dimension_status(
            args.container,
            outcome_id,
            dimension="role",
            status=mapping["role_status"],
            rationale=rationale,
        )
        update_dimension_status(
            args.container,
            outcome_id,
            dimension="bridge",
            status=mapping["bridge_status"],
            rationale=rationale,
        )

        replace_candidate_links(
            args.container,
            table="outcome_time_link",
            value_column="time_class",
            outcome_id=outcome_id,
            values=mapping.get("time_classes", []),
            rationale=rationale,
        )
        replace_candidate_links(
            args.container,
            table="outcome_transfer_axis",
            value_column="transfer_axis",
            outcome_id=outcome_id,
            values=mapping.get("transfer_axes", []),
            rationale=rationale,
        )
        replace_candidate_links(
            args.container,
            table="outcome_role_link",
            value_column="outcome_role",
            outcome_id=outcome_id,
            values=mapping.get("outcome_roles", []),
            rationale=rationale,
        )
        replace_candidate_links(
            args.container,
            table="outcome_bridge_evidence",
            value_column="bridge_evidence",
            outcome_id=outcome_id,
            values=mapping.get("bridge_evidence", []),
            rationale=rationale,
        )

        outcome_count += 1
        time_links += len(mapping.get("time_classes", []))
        transfer_links += len(mapping.get("transfer_axes", []))
        role_links += len(mapping.get("outcome_roles", []))
        bridge_links += len(mapping.get("bridge_evidence", []))

    print(
        "STAGE 4 CANDIDATE MAPPINGS APPLIED: "
        f"outcomes={outcome_count}; time_links={time_links}; "
        f"transfer_links={transfer_links}; role_links={role_links}; "
        f"bridge_links={bridge_links}"
    )
    print("All Stage 4 candidate mappings remain review_status=proposed / mapping_source=agent_candidate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
